version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - MONGO_SECRET_KEY=mongodb://mongo:27017/myapp
      - JSON_WEB_TOKEN_SECRET_KEY=sSeMvhbk5bPDSzpf274B9uFLK49oL2N1IRD1WDbSCRjleyo4tiwqA11aTZntRYkp
      - PORT=80
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=1234
      - GOOGLE_CLIENT_ID=1038559422623-l7dj52bstjtaluifimmp94i1sil4936h.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost/api/auth/google-login/callback
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    command: mongod --port 27017
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local